PetShopWebApp/Controllers/AdminController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PetShop.Backend.Repositories;
using PetShop.Shared.Models;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace PetShopWebApp.Controllers
{
    public class AdminController : Controller
    {
        private readonly IPetShopRepository _repo;
        private readonly IWebHostEnvironment _env;
        private readonly List<Category> _categories;
        public AdminController(IPetShopRepository repo,IWebHostEnvironment env)
        {
            _repo = repo;
            _env = env;
            _categories = _repo.GetAllCategories();
        }
        /// <summary>
        /// returns view with all the animals
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            ViewBag.Categories = _categories;
            var animals = _repo.GetAllAnimals();
            return View(animals);
        }
        /// <summary>
        /// returns view with all the animal of the chosen category
        /// </summary>
        /// <param name="categoryId"></param>
        /// <returns></returns>
        public IActionResult Category(int categoryId)
        {
            var relevantAnimals = _categories.
               FirstOrDefault(c => c.CategoryId == categoryId)
               .Animals.ToList();
            ViewBag.Categories = _categories;
            return View("Index", relevantAnimals);
        }

        /// <summary>
        /// returns form to edit exist animal
        /// </summary>
        /// <param name="animalId"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Edit(int animalId)
        {
            var animal = _repo.GetAllAnimals().FirstOrDefault(a => a.AnimalId == animalId);
            ViewBag.Animal = animal;
            return View(animal);
        }

        /// <summary>
        /// post method to edit action , checks the model validity and updates it in database
        /// </summary>
        /// <param name="newAnimal"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Edit(Animal newAnimal)
        {
            if(ModelState.IsValid)
            {
                CheckImageFile(newAnimal);
                _repo.UpdateAnimal(newAnimal);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }


        /// <summary>
        /// Delete the animal with the given id.
        /// </summary>
        /// <param name="animalId"></param>
        /// <returns></returns>
        public IActionResult Delete(int animalId)
        {
            _repo.RemoveAnimal(animalId);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// returns form to add new animal to the store
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Add()
        {
            var categories = _repo.GetAllCategories().AsEnumerable();
            var selectList = new List<SelectListItem>();
            foreach (var cat in categories)
            {
                selectList.Add(new SelectListItem { Text = cat.CategoryName, Value = cat.CategoryId.ToString() });
            }
            ViewBag.Categories = selectList;
            return View();
        }

        /// <summary>
        /// post method to the add action , checks the model validity and adds it to the database
        /// </summary>
        /// <param name="animal"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Add(Animal animal)
        {
            if (ModelState.IsValid)
            {
                CheckImageFile(animal);
                _repo.AddAnimal(animal);
                return RedirectToAction("Index");
            }
            else
                return RedirectToAction("Add");
        }

        /// <summary>
        /// Checks if the user uploaded image , adds it to the img folder and gives the animal its picture name
        /// </summary>
        /// <param name="animal"></param>
        public void CheckImageFile(Animal animal)
        {
            if (animal.PictureFile != null)
            {
                var folder = @"\Assets\AnimalImgs\";
                var serverFolder = _env.WebRootPath + folder;
                if (!Directory.Exists(serverFolder))
                {
                    Directory.CreateDirectory(serverFolder);
                }

                var fileName = Path.GetFileName(animal.PictureFile.FileName);
                string fullPath = serverFolder + fileName;

                using (var fileStream = new FileStream(fullPath, FileMode.Create))
                {
                    animal.PictureFile.CopyTo(fileStream);
                }
                animal.PictureName = "/Assets/AnimalImgs/" + fileName;
            }
        }

    }
}

PetShopWebApp/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using PetShop.Backend.Repositories;
using PetShop.Shared.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PetShopWebApp.Controllers
{
    public class CatalogController : Controller
    {
        readonly IPetShopRepository _repo;
        private readonly List<Category> _categories;

        public CatalogController(IPetShopRepository Repository)
        {
            _repo = Repository;
            _categories = _repo.GetAllCategories();
        }

        /// <summary>
        /// returns view with All the animals from the database
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            ViewBag.Categories = _categories;
            ViewBag.Animals = _repo.GetAllAnimals();
            return View();
        }
        /// <summary>
        /// returns view all the animals of the selcted category
        /// </summary>
        /// <param name="categoryId"></param>
        /// <returns></returns>
        public IActionResult Category(int categoryId)
        {
            var relevantAnimals = _categories.
                FirstOrDefault(c => c.CategoryId == categoryId)
                .Animals.ToList();
            ViewBag.Categories = _categories;
            ViewBag.Animals = relevantAnimals;
            return View("Index");
        }
        /// <summary>
        /// returns page with details about the selcted animal 
        /// </summary>
        /// <param name="animalId"></param>
        /// <returns></returns>
        public IActionResult AnimalDes(int animalId)
        {
            var animal = _repo.GetAllAnimals().FirstOrDefault(a => a.AnimalId == animalId);

            return View(animal);
        }

        /// <summary>
        /// Checks the comment validity and adds it to the database
        /// </summary>
        /// <param name="comment"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult AddComment(Comment comment)
        {
            if ( ModelState.IsValid)
            {
                comment.Date = DateTime.Now;
                _repo.AddComment(comment);
                return RedirectToAction("AnimalDes", new { comment.AnimalId });
            }
            return RedirectToAction("AnimalDes", new { comment.AnimalId });
        }
    }
}

PetShopWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PetShop.Backend.Repositories;
using PetShop.Shared.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PetShopWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPetShopRepository _repo;
        public HomeController(IPetShopRepository repo)
        {
            _repo = repo;
        }
        /// <summary>
        /// Returns view with the two most commented animals in the database
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            var ansToShow = _repo.GetAllAnimals()
                .OrderByDescending(a => a.Comments.ToList().Count)
                .ToList()
                .Take(2)
                .ToList();
            return View(ansToShow);
        }
    }
}

PetShopWebApp/Views/Admin/Add.cshtml
@model Animal
@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<script src="~/lib/jquery/jquery.js" ></script>
<script src="~/lib/validation/jquery.validate.min.js" ></script>
<script src="~/lib/validation/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js" ></script>
<link rel="stylesheet" href="~/css/AdminStyle/AdminAddStyleSheet.css" />

<div id="form-control">
    <form asp-controller="Admin" asp-action="Add" method="post" enctype="multipart/form-data">
        @Html.LabelFor(a => a.CategoryId)
        @Html.DropDownListFor(a => a.CategoryId, new List<SelectListItem>(ViewBag.Categories))
        @Html.ValidationMessageFor(a => a.AnimalId, "", new { @class = "error" })

        @Html.LabelFor(a => a.Name)
        @Html.EditorFor(a => a.Name)
        @Html.ValidationMessageFor(a => a.Name, "", new { @class = "error" })

        @Html.LabelFor(a => a.Age)
        @Html.EditorFor(a => a.Age)
        @Html.ValidationMessageFor(a => a.Age, "", new { @class = "error" })

        @Html.LabelFor(a => a.PictureFile)
        @Html.EditorFor(a => a.PictureFile)

        @Html.LabelFor(a => a.PictureName)
        @Html.EditorFor(a => a.PictureName)
        @Html.ValidationMessageFor(a => a.PictureName, "", new { @class = "error" })

        @Html.LabelFor(a => a.Description)
        @Html.TextAreaFor(a => a.Description, new { @placeholder = "Description...." })
        @Html.ValidationMessageFor(a => a.Description, "", new { @class = "error" })

        <button type="submit" id="btn-sbmt">Add Animal</button>
    </form>
</div>

PetShopWebApp/Views/Admin/Edit.cshtml
@model Animal
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/lib/jquery/jquery.js"></script>
<script src="~/lib/validation/jquery.validate.min.js"></script>
<script src="~/lib/validation/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<link rel="stylesheet" href="~/css/AdminStyle/AdminEditStyleSheet.css" />


<div id="form-control">
    <form method="post" asp-controller="Admin" asp-action="Edit" enctype="multipart/form-data">

        @Html.HiddenFor(a => a.AnimalId)
        @Html.HiddenFor(a => a.CategoryId)

        @Html.LabelFor(a => a.Name)
        @Html.EditorFor(a => a.Name)
        @Html.ValidationMessageFor(a => a.Name, "", new { @class = "error" })

        @Html.LabelFor(a => a.Age)
        @Html.EditorFor(a => a.Age)
        @Html.ValidationMessageFor(a => a.Age, "", new { @class = "error" })

        @Html.LabelFor(a => a.PictureFile)
        @Html.EditorFor(a => a.PictureFile)

        @Html.LabelFor(a => a.PictureName)
        @Html.EditorFor(a => a.PictureName)
        @Html.ValidationMessageFor(a => a.PictureName, "", new { @class = "error" })


        @Html.LabelFor(a => a.Description)
        @Html.EditorFor(a => a.Description)
        @Html.ValidationMessageFor(a => a.Description, "", new { @class = "error" })

        <button id="sbmt" type="submit">Save Changes</button>

    </form>
</div>

PetShopWebApp/Views/Admin/Index.cshtml
@model List<Animal>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/css/AdminStyle/AdminStyleSheet.css" />
<script src="~/scripts/AdminScripts/AdminIndex.js"></script>
<div id="new-animal">
    <a id="btn-add-new" href="/Admin/Add">Add New Animal</a>
</div>
<div id="drop-down-category">
    <select id="cat">
        <option disabled selected>Select Category</option>
        @foreach (var cat in ViewBag.Categories)
        {
            <option value="@cat.CategoryId">@cat.CategoryName</option>
        }
    </select>
    <a id="btn-submit" data-url-prefix="@Url.Action("Category")">Submit</a>
</div>
<div class="admin">
    @foreach (var an in Model)
    {
        await Html.RenderPartialAsync("AdminCatalogPartial", an);
    }
</div>

PetShopWebApp/Views/Catalog/AnimalDes.cshtml
@model Animal
@{
    ViewData["Title"] = "AnimalDes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/css/CatalogStyle/AnimalDesStyleSheet.css" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="~/lib/jquery/jquery.js"></script>
<script type="text/javascript" src="~/scripts/Catalog/Catalog.js"></script>

<div id="contain">
    <div id="pic">
        <img id="anim-img" src="@Model.PictureName" alt="">
    </div>
    <div id="name">
        <h1>@Model.Name</h1>
    </div>
    <div id="category">
        <h2>Category : @Model.Category.CategoryName</h2>
    </div>
    <div id="information">
        <h2>Age: @Model.Age</h2>
        <p>
            <h3>Description: </h3>
            @Model.Description
        </p>
    </div>

    <div class="container">
        <h1>Comments</h1>
        <div class="row">
            <div class="col-sm-5 col-md-6 col-12 pb-4">
                @foreach (var com in Model.Comments)
                {
                    <div class="comment mt-4 text-justify float-left">
                        <img src="https://i.imgur.com/CFpa3nK.jpg" alt="" class="rounded-circle" width="40" height="40">
                        <h4>@com.WriterName</h4> <span>-@com.Date.ToString("dd-MM-yyyy(hh:mm)")</span> <br>
                        <p>@com.CommentInfo</p>
                    </div>
                }
            </div>
            <div class="col-lg-4 col-md-5 col-sm-4 offset-md-1 offset-sm-1 col-12 mt-4" id="add-comment">
                <partial name="CommentsPartial" model="new Comment { AnimalId = Model.AnimalId }" />
            </div>
        </div>
    </div>
</div>

PetShopWebApp/Views/Catalog/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/css/CatalogStyle/CatalogStyleSheet.css" />
<script src="~/lib/jquery/jquery.js"></script>
<script type="text/javascript" src="~/scripts/Catalog/Catalog.js"></script>
<div class="catalog">
    <div class="catalog-info">
        <div id="drop-down-category">
            <select id="cat">
                <option disabled selected>Select Category</option>
                @foreach (var cat in ViewBag.Categories)
                {
                    <option value="@cat.CategoryId">@cat.CategoryName</option>
                }
            </select>
            <a id="btn-submit" data-url-prefix="@Url.Action("Category")">Submit</a>
        </div>
        <div id="all-animals">
            @foreach (var an in ViewBag.Animals)
            {
                <partial name="AnimalCatalogPartial" for="@an" />
            }
        </div>
    </div>
</div>

PetShopWebApp/Views/Home/Index.cshtml
@model List<Animal>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/css/HomeStyle/HomeStyleSheet.css" />
 <h1>Most Popular Animals Today :</h1>
<div class="home">
    @foreach (var an in Model)
    {
        <div class="animal">
            @{
                await Html.RenderPartialAsync("AnimalCatalogPartial", an);
            }
            <div>
                <h3>Number of Comments : @an.Comments.Count()</h3>
            </div>
        </div>
    }
</div>

PetShopWebApp/Views/Shared/AdminCatalogPartial.cshtml
@model Animal

<link rel="stylesheet" href="~/css/AdminCatalogStyleSheet.css" />
<div id="unit-component">
    @{ 
        await Html.RenderPartialAsync("AnimalCatalogPartial",Model);
    }
    <div id="admin-addition">
        <a id="btn-edit" asp-controller="Admin" asp-action="Edit" asp-route-animalId="@Model.AnimalId">
            <img class="icon" src="~/Assets/edit_128px.png"/>
        </a>
        <a id="btn-delete" asp-controller="Admin" asp-action="Delete" asp-route-animalId="@Model.AnimalId">
            <img class="icon" src="~/Assets/icons8_remove_200px_1.png"/>
        </a>
    </div>
</div>

PetShopWebApp/Views/Shared/AnimalCatalogPartial.cshtml
@model Animal

<link rel="stylesheet" href="~/css/CatalogPartialStyleSheet.css" />
<div class="partial-catalog">
    <div>
        <img class="modelImg" src="@Model.PictureName" />
    </div>
    <div class="info-name">
        <a id="btn-name" asp-controller="Catalog" asp-action="AnimalDes" asp-route-animalId="@Model.AnimalId">@Model.Name</a>
    </div>
</div>

PetShopWebApp/Views/Shared/CommentsPartial.cshtml
@model Comment

<script src="~/lib/jquery/jquery.js"></script>
<script src="~/lib/validation/jquery.validate.min.js"></script>
<script src="~/lib/validation/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<link rel="stylesheet" href="~/css/CommentsPartialStyleSheet.css" />

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<form id="algin-form" method="post" asp-action="AddComment">
    @Html.HiddenFor(c=>c.AnimalId)
    <div class="form-group">
        <h4 id="label">Leave a comment</h4>
        @Html.LabelFor(c=>c.CommentInfo, new { @class = "label" })
        @Html.EditorFor(c=>c.CommentInfo,new {@class = "form-control" })
        <br />
        @Html.ValidationMessageFor(c => c.CommentInfo, "", new { @class = "wrong" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.WriterName,new { @class = "label" })
        @Html.EditorFor(c => c.WriterName, new { @class = "form-control"})
        <br />
        @Html.ValidationMessageFor(c => c.WriterName, "", new { @class = "wrong" })
    </div>
    <div class="form-group"> 
        <button type="submit" id="post" class="btn">Add Comment</button> 
    </div>
</form>

PetShopWebApp/Views/Shared/EditPartialView.cshtml
@model Animal

<div id="form-control">
    <form method="post" asp-controller="Admin" asp-action="Edit" asp-route-newAnimal="@Model">
        <div>
            @Html.LabelFor(a => a.Name)
            @Html.EditorFor(a => a.Name)
            <button type="button" class="dont" data-txt="name">Dont Change</button>
            @Html.ValidationMessageFor(a => a.Name, "", new { @class = "error" })
        </div>
        <div>
            @Html.LabelFor(a => a.Age)
            @Html.EditorFor(a => a.Age)
            <button type="button" class="dont" data-txt="age">Dont Change</button>
            @Html.ValidationMessageFor(a => a.Age, "", new { @class = "error" })
        </div>
        <div>
            @Html.LabelFor(a => a.PictureName)
            @Html.EditorFor(a => a.PictureName)
            <button type="button" class="dont" data-txt="img-name">Dont Change</button>
            @Html.ValidationMessageFor(a => a.PictureName, "", new { @class = "error" })
        </div>
        <div>
            @Html.LabelFor(a => a.Description)
            @Html.EditorFor(a => a.Description)
            <button type="button" class="dont" data-txt="desc">Dont Change</button>
            @Html.ValidationMessageFor(a => a.Description, "", new { @class = "error" })
        </div>
        <div>
            <input id="sbmt" type="submit" value="Save Changes" />
        </div>
    </form>
</div>

PetShopWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/css/LayoutStyleSheet.css" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script type="text/javascript" src="~/scripts/Shared/Layout.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    @*Header*@
    <div id="head">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="single-page-nav sticky-wrapper" id="tmNavbar">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Homepage</a></li>
                        <li><a asp-controller="Catalog" asp-action="Index">Catalog</a></li>
                        <li><a asp-controller="Admin" asp-action="Index">Administration</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>


    <div id="body-render">
        @RenderBody()
    </div>


    @*Footer*@
    <div id="slider">
        <ul class="slides">
            <li class="slide"><img src="~/Assets/final/combine_images.jpg"></li>
            <li class="slide"><img src="~/Assets/final/combine_images (1).jpg"></li>
            <li class="slide"><img src="~/Assets/final/combine_images (2).jpg"></li>
            <li class="slide"><img src="~/Assets/final/combine_images (3).jpg"></li>
            <li class="slide"><img src="~/Assets/final/combine_images.jpg"></li>
        </ul>
    </div>
</body>
</html>